### ISSUE TITLE
Adding of basic "lowercase" and "UPPERCASE" ?

### ISSUE THREAD

**Issue by cotwitch** [zhengxiaoyao0716/vscode-intelligence-change-case#1]
Hi Water Zheng!
Did you mind about adding "basic/elementary case" types - "lowercase" and "UPPERCASE" to your great vscode extension?

Or will you eventually accept pull request if'll do it by myself?

Regards

**Comment by zhengxiaoyao0716** [comment]
I‘m not sure what's your mean, if you need `snake_case` or `CONST_CASE`, it has already supported, just change the settings to join the case you need into the option `change-case.${language}`.
But if you really need something looks like `snakecase` or `CONSTCASE` without `_`, let's think it carefully. Although it's easy to support them just by removed `_` from `snake_case` and `CONST_CASE`, but if we do it, the separator of the word would lost, then how could it transform back to other case?(This plugin used `Ctrl+U` to transform the word case between configurated options).

**Comment by cotwitch** [comment]
Thanks for reply! While I have understanding for your argument, I've just found this extension which implements desired behavior somehow: https://marketplace.visualstudio.com/items?itemName=PranshuAgrawal.toggle-case
