### ISSUE TITLE
Add options to change to different cases

### ISSUE THREAD

**Issue by mwpowellhtx** [zhengxiaoyao0716/vscode-intelligence-change-case#2]
Is there only an option to toggle to/from camel case, etc? Would be fantastic if more cases were allowed, or even pattern matched, trained, etc.

**Comment by zhengxiaoyao0716** [comment]
You can find some preset change-case options [here](https://github.com/zhengxiaoyao0716/vscode-intelligence-change-case/blob/master/package.json#L32-L110) .

It looks for change-case rules in the options of `VSCode` named `change-case.${fileExt}`, and it used `change-case.default` as the default rules if not found. (https://github.com/zhengxiaoyao0716/vscode-intelligence-change-case/blob/master/src/change-case.ts#L8-L9)

**Comment by zhengxiaoyao0716** [comment]
`pattern matched and trained` might be a good idea but a bit complicated, I've not enough ability and energy to realize it.
