### ISSUE TITLE
Possibility to toggle case for word without highlighting it

### ISSUE THREAD

**Issue by AlexSapoznikov** [zhengxiaoyao0716/vscode-intelligence-change-case#3]
It would be amazing if it would be possible to trigger case change on the word(s) that cursor is placed at without highlighting it (in addition to current implementation of highlighting it).

**Comment by zhengxiaoyao0716** [comment]
completed. [commit#19bea6df7d584e218b3e33863cb1c680f37b76ec](https://github.com/zhengxiaoyao0716/vscode-intelligence-change-case/commit/19bea6df7d584e218b3e33863cb1c680f37b76ec)

**Comment by AlexSapoznikov** [comment]
Thank you so much! :)
